site_name: Sistemas Hardware-Software - 2020/2
site_author: Igor Montagner

extra:
    materia: Sistemas Hardware-Software
    professor: Igor Montagner
    semestre: 2020/2

theme:
  feature:
    tabs: true
  name: 'material'
  palette:
    scheme: preference
    primary: brown
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono
  custom_dir: 'custom_theme'

docs_dir: material
site_dir: docs

repo_url: https://github.com/insper/sistemashardwaresoftware
repo_name: "sistemashardwaresoftware"
site_url: https://insper.github.io/SistemasHardwareSoftware/


nav:
    - Home: index.md
    - Burocracias: sobre.md

    - Aulas:
        - aulas/01-introducao/index.md
        - aulas/02-inteiros/index.md
        - aulas/03-ram/index.md
        - aulas/04-asm-1/index.md
        - aulas/05-funcoes/index.md
        - aulas/06-condicionais/index.md
        - aulas/07-loops/index.md
        - aulas/08-variaveis-locais/index.md
        - aulas/09-arrays/index.md
        - aulas/10-malloc/index.md
        - aulas/11-tipos-de-dados/index.md
        - aulas/12-linux-do-zero/index.md
        - aulas/13-entrada-saida/index.md
        - aulas/14-processos/index.md
        - aulas/15-exec/index.md
        - aulas/16-sinais-1/index.md
        - aulas/17-sinais-2/index.md
        - aulas/18-threads/index.md
        - aulas/99-corretor-automatico.md

    - Projetos:
        - projetos/bomblab.md
        - projetos/posix.md



extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS_HTML
    - translate-admonitions.js

extra_css:
    - css/printing.css

markdown_extensions:
  - markdown.extensions.tables
  - tables
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      base_path: code
      check_paths: true
plugins:
    - search
